image: public.ecr.aws/sam/build-python3.12:latest

stages:
  - build
  - deploy

build_api:
  stage: build
  script:
    - echo "Construction de l'application Serverless..."
    - sam build
  artifacts:
    paths:
      - .aws-sam/

deploy_api:
  stage: deploy
  script:
    - echo "Déploiement sur AWS via LabRole..."
    - sam deploy 
        --stack-name mon-api-gitlab-stack 
        --no-confirm-changeset 
        --no-fail-on-empty-changeset
        --capabilities CAPABILITY_IAM 
        --region us-east-1
        --role-arn arn:aws:iam::907354788138:role/LabRole 
        --resolve-s3
  only:
    - main